[package]
name = "earley-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
rustc-hash = "2.1.1"

[lints.clippy]
all = "allow"
complexity = "warn"
perf = "warn"
suspicious = "warn"
correctness = "deny"
